### ISSUE TITLE
Backup Tracks with "tee" And The "extern" Option

### ISSUE THREAD

**Issue by gamrot** [jkramer/shell-fm#2] opened 2009-10-04 21:25 UTC
I was following instructions posted on http://shell-fm.wikidot.com/hack:extern-tee-backup but when I press n (for next song) I get an error: audio: /dev/dsp: Device or resource busy.

I believe the problem is the new version of the play.c file, since the guide was written before version 0.7 was published.

Here is what I wrote in shell-fm.rc file:
download = /home/mgamrot/music/lastfm/%a;%t;%l;%d.mp3
extern = tee "/home/mgamrot/music/lastfm/%a - %l - %t.mp3" | madplay -Q -

I'm using Cranchbang Linux 9.04.

**Comment by jkramer** [comment] 2009-10-06 18:34
Fixed with commit  de90c5147d4daff5a28cec0000ee343cbf96f1fd. The problem is that shell-fm didn't wait until the external player finished before starting the next one with the next track.

**Closed as completed by jkramer** 2009-10-06 18:34 UTC
