### ISSUE TITLE
deamon mode hangs upon commands

### ISSUE THREAD

**Issue by neurino** [jkramer/shell-fm#16] opened 2010-09-27 21:54 UTC
Self-explanatory:
$ shell-fm -i localhost -p 54311 -d

$ echo "info %v" | nc localhost 54311

prints "100%" then hangs, I tried a lot of commands and now they all sit in my ps

$ ps | grep nc
13214 root       0:00 nc localhost 54311
13393 root       0:00 nc localhost 54311
13588 root       0:00 nc localhost 54311
13982 root       0:00 nc localhost 54311
14205 root       0:00 nc localhost 54311
19176 root       0:00 nc localhost 54311
28882 root       0:00 grep nc

I compiled it in PuppyLinux.
Old version 0.7 never gave problems (except did not scrobbled and that's why I updated it)

Thanks for your support

**Comment by neurino** [comment] 2010-09-29 09:11
So no answers? It only happens to me???

In the meanwhile I restored old version, the one that did not scrobbled...

Thank you

**Comment by postmann** [comment] 2010-11-21 19:49
Possibly this is due to standard-netcat behavior. Netcat waits until the connection is closed by the "other side". There's an "-q time_in_seconds" option which quits netcat after x seconds.

**Comment by neurino** [comment] 2010-11-22 08:28
I worked flawlessly without any option to nc before so I wonder why can't this be restored also in last version...

Also wait `x` seconds is not what I call a good response to a command in a software... :)

Cheers

**Comment by jkramer** [comment] 2011-02-19 12:27
Sorry for ignoring you. shell-fm doesn't directly close your session after the first command anymore, but you're now able to send multiple commands, one per line. The session will stay open until you send the "detach" command. So it's a feature, not a bug. :)

**Comment by neurino** [comment] 2011-02-19 14:05
well I compiled last source from repo time ago and did not experience the same problem again... strange.
So you say I should send a command and then follow with `detach` to get response?

I need it for this: 
http://murga-linux.com/puppy/viewtopic.php?t=59777

I'll check it out, thanks.

**Closed as completed** 2011-02-19 20:27 UTC
