### ISSUE TITLE
problems scrobbling with api2

### ISSUE THREAD

**Issue by kitwestneat** [jkramer/shell-fm#68] opened 2012-11-28 20:57 UTC
I have been trying out the new version of shell-fm today and ran into some issues with scrobbling. At first it seemed to submit the same songs over and over, then I got this error:

Now playing "Un Jour Tu Verras" by Mouloudji.
Failed to scrobble track(s). Invalid Method - No method with that name in this package.
Now playing "Generator ^ First Floor" by Freelance Whales.
Invalid HTTP: HTTP/1.0 400 Bad Request
  from: http://ws.audioscrobbler.com/2.0/
Now playing "Pelo Tempo Que Durar" by Marisa Monte.
Failed to scrobble track(s). Indexed scrobbles must be continuous, missing index 0..
Failed to scrobble track(s). Indexed scrobbles must be continuous, missing index 0..
Now playing "We Come Running" by Youngblood Hawke.

Do you think it might have something to do with the ^ symbol in the song title?

When I restarted shell-fm, I got:
Invalid authentication token supplied..
Failed to create session. Please refresh authorization.
Please open http://www.last.fm/api/auth/?token=f45da3513d2f9650633641ba44732358&api_key=cc299dde20a9ae5dbb63118c65cbcc85 in your browser to authorize shell-fm.

Are there any debug options I can run shell-fm or any information I can gather to help? Thanks.

**Comment by kitwestneat** [comment] 2012-11-28 21:17
Here's an example of the multiple scrobble problem:

Maria Rita – Novo Amor            3 minutes ago  
Heike has the giggles – The Bride         6 minutes ago  
Heike has the giggles – The Bride         6 minutes ago  
Beulah – Hovering         9 minutes ago  
Beulah – Hovering         9 minutes ago  
Beulah – Hovering         9 minutes ago  
Ladytron – Ace of Hz          14 minutes ago  
Ladytron – Ace of Hz          14 minutes ago  
Ladytron – Ace of Hz          14 minutes ago  
Ladytron – Ace of Hz          14 minutes ago  
Marisa Monte – Balança Pema          17 minutes ago  
Marisa Monte – Balança Pema          17 minutes ago  
Marisa Monte – Balança Pema          17 minutes ago  
Marisa Monte – Balança Pema          17 minutes ago  
Marisa Monte – Balança Pema          17 minutes ago  

It looks like it's clearing the queue after it submits it, or something like that.

**Comment by jkramer** [comment] 2012-11-28 22:25
I think I know what the problem is. I'm not home right now and can't look at the code, but if you know a little C, you might try adding this to the end of submit() in submit.c, just before the return:

queue_length = 0;
empty(& queue), // this one might be already there

I'll fix it tomorrow.
-----Original Message-----

**Comment by kitwestneat** [comment] 2012-11-29 06:16
I think it'd have to be added to subdead() since the submit() exits at the
end. I added some debug messages and it looks like submit() is always
returning -1 (which becomes 255). I changed retval to be initialized to 0
and that seems to work. I'll submit a patch.

**Comment by jkramer** [comment] 2012-11-29 08:55
Yeah you're right, thanks for the patch. Just merged it.

**Closed as completed by jkramer** 2012-11-29 08:55 UTC
